### PR TITLE
add __init__ file and preview to what pylint + black do

### PR DESCRIPTION
**Pull request by Matuiss2**
Just some very small changes for feedback(not much to be changed yet, but maybe its enough to get the idea):

I used black for formatting and pylint for other readability changes and cleaning
https://github.com/ambv/black
https://github.com/PyCQA/pylint

Tell me if its the way you want the code to look, or if you need more

### CODE REVIEW

**Comment by kiudee** [comment]
LGTM, are you planning to rebase the fix commit? Otherwise, I can just squash & merge.

**Comment by inoryy** [comment]
I'm not sure I see the benefit of using black over PEP8

**Comment by Matuiss2** [comment]
In this case, there is no difference, but autoPEP8 and Black have some small differences.

**Comment by inoryy** [comment]
This PR looks good, but in general I guess we'd need to discuss which code style to follow, from discord discussion seemed like people were in favor of PEP8

**Comment by kiudee** [comment]
Ok, I will merge this and we can continue discussion in Discord.

**Pull request merged**
